CREATE TABLE DIM_EX_CARCACA(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    CARCACAMINIMO VARCHAR(10),
    TAMPAMAXIMO VARCHAR(10),
    FOLGAMAXIMA VARCHAR(255),
    XMINIMO VARCHAR(10),
    YMINIMO VARCHAR(10),
    MINIMOCOMPPASSCHAMA VARCHAR(10),
    PRIMARY KEY(CODCONTROLE)
);

COMMENT ON COLUMN DIM_EX_CARCACA.CARCACAMINIMO IS 'Ø minimo da carcaça';
COMMENT ON COLUMN DIM_EX_CARCACA.TAMPAMAXIMO IS 'Ø maximo da tampa';
COMMENT ON COLUMN DIM_EX_CARCACA.FOLGAMAXIMA IS 'ØTmax - ØCmin';
COMMENT ON COLUMN DIM_EX_CARCACA.MINIMOCOMPPASSCHAMA IS 'y+x';

CREATE INDEX IDX_CRC_CARCACA ON DIM_EX_CARCACA (CARCACA);
CREATE INDEX IDX_CRC_LINHA ON DIM_EX_CARCACA (LINHA);
CREATE INDEX IDX_CRC_CARC_LINHA ON DIM_EX_CARCACA (CARCACA, LINHA);

CREATE SEQUENCE dim_ex_carcaca
MINVALUE 1
START WITH 1
INCREMENT BY 1;