CREATE TABLE DIM_EX_ANEL_FIXACAO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    POLOS INTEGER,
    WDIANT VARCHAR(15),
    W1DIANT VARCHAR(15),
    W2DIANT VARCHAR(15),
    W3DIANT VARCHAR(15),
    WTRAS VARCHAR(15),
    W1TRAS VARCHAR(15),
    W2TRAS VARCHAR(15),
    W3TRAS VARCHAR(15),
    COMPPASSCHAMAANELL VARCHAR(15),
    DIAMPASSCHAMAANELADIANT VARCHAR(15),
    DIAMPASSCHAMAANELATRAS VARCHAR(15),
    DIAMPASSCHAMAEIXOEDIANT VARCHAR(15),
    DIAMPASSCHAMAEIXOETRAS VARCHAR(15),
    FOLGAMAXIMADIANT VARCHAR(15),
    FOLGAMAXIMATRAS VARCHAR(15),
    PRIMARY KEY(CODCONTROLE)
);

CREATE INDEX IDX_ANF_CARCACA ON DIM_EX_ANEL_FIXACAO (CARCACA);
CREATE INDEX IDX_ANF_LINHA ON DIM_EX_ANEL_FIXACAO (LINHA);
CREATE INDEX IDX_ANF_CARC_LINHA ON DIM_EX_ANEL_FIXACAO (CARCACA, LINHA);

CREATE SEQUENCE dim_ex_anel_fix
MINVALUE 1
START WITH 1
INCREMENT BY 1;