CREATE TABLE CAD_SERVICOS(
    CODSERVICO BIGINT,
    DESCRICAOSERVICO VARCHAR(255),
    VALORVENDA DECIMAL(12,2),
    PRIMARY KEY(CODSERVICO)
);

CREATE INDEX IDX_DESCRICAO_SERV ON CAD_SERVICOS(DESCRICAOSERVICO);

CREATE SEQUENCE seq_servicos
MINVALUE 1
START WITH 1
INCREMENT BY 1;