CREATE TABLE CAD_PRODUTO (
    CODIGOPRODUTO BIGINT NOT NULL,
    CODIGOPRODFORNECEDOR VARCHAR(255),
    CODIGO_BARRAS VARCHAR(255),
    DATACADASTRO TIMESTAMP,
    GRUPO BIGINT,
    NCM_SH BIGINT,
    MARCA VARCHAR(255),
    DESCRICAOPRODUTO VARCHAR(255),
    QUANTIDADE DECIMAL(12, 3),
    ESTOQUEMINIMO BIGINT,
    UNIDADE VARCHAR(3),
    VALORUNITPRODUTO DECIMAL(12, 3),
    VALORTABELAWEG DECIMAL(12, 3),
    FATORVALORVENDA BIGINT,
    IPI BIGINT,
    ICMS BIGINT,
    ATIVO BOOLEAN,
    USOOFICINA BOOLEAN,
    VERIFICAZERO BOOLEAN,
    LOCALIZACAO VARCHAR(255),
    PRIMARY KEY(CODIGOPRODUTO)
);

CREATE INDEX IDX_COD_PROD_FORNEC ON CAD_PRODUTO(CODIGOPRODFORNECEDOR);
CREATE INDEX IDX_DESC_PROD ON CAD_PRODUTO(DESCRICAOPRODUTO);
CREATE INDEX IDX_DT_CADASTRO ON CAD_PRODUTO(DATACADASTRO);

CREATE SEQUENCE seq_cod_prod_fornec
MINVALUE 1
START WITH 1
INCREMENT BY 1;