CREATE TABLE DIM_EX_PONTA_EIXO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    MINIMO2 DECIMAL(12,3),
    MAXIMO2 DECIMAL(12,3),
    DIAMPONTAEIXO VARCHAR(10),
    RDEIXO VARCHAR(10),
    MINIMO VARCHAR(10),
    MAXIMO VARCHAR(10),
    BATIMENTO VARCHAR(10),
    DIAMCOLOVENTILADOR VARCHAR(10),
    RDCOLOVENTILADOR VARCHAR(10),
    COLOVENTMINIMO VARCHAR(10),
    COLOVENTMINIMO2 VARCHAR(255),
    COLOVENTMAXIMO VARCHAR(10),
    COLOVENTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);

CREATE INDEX IDX_PTE_CARCACA ON DIM_EX_PONTA_EIXO (CARCACA);
CREATE INDEX IDX_PTE_POLOS ON DIM_EX_PONTA_EIXO (POLOS);
CREATE INDEX IDX_PTE_LINHA ON DIM_EX_PONTA_EIXO (LINHA);
CREATE INDEX IDX_PTE_CARC_LINHA ON DIM_EX_PONTA_EIXO (CARCACA, LINHA);
CREATE INDEX IDX_PTE_CARC_PL_LINHA ON DIM_EX_PONTA_EIXO (CARCACA, POLOS, LINHA);

CREATE SEQUENCE dim_ex_ponta_eixo
MINVALUE 1
START WITH 1
INCREMENT BY 1;