/*CAD_MARCAS*/
CREATE TABLE CAD_MARCAS(CODIGO BIGINT NOT NULL, MARCA VARCHAR(255) NOT NULL, PRIMARY KEY(CODIGO));
CREATE INDEX IDX_MARCA ON CAD_MARCAS(MARCA);
CREATE SEQUENCE seq_cad_marcas MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_ASSINATURAS*/
CREATE TABLE CAD_ASSINATURAS(CODIGO BIGINT NOT NULL, NOME VARCHAR(30), SENHA VARCHAR(8), ASSELETRONICA BLOB, PRIMARY KEY(CODIGO));
CREATE INDEX IDX_NOME ON CAD_ASSINATURAS(NOME);
CREATE SEQUENCE seq_assinaturas MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_CATEGORIAS*/
CREATE TABLE CAD_CATEGORIAS(CODIGO BIGINT NOT NULL, DESCRICAO VARCHAR(100) NOT NULL, PRIMARY KEY(CODIGO));
CREATE INDEX IDX_DESCRICAO ON CAD_CATEGORIAS(DESCRICAO);
CREATE SEQUENCE seq_cad_categorias MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_CLASSIFICACAO_FORNEC*/
CREATE TABLE CAD_CLASSIFICACAO_FORNEC(CODCLASSIFICACAO BIGINT, DESCRICAOCLASSIFICAO VARCHAR(255), PRIMARY KEY(CODCLASSIFICACAO));
CREATE SEQUENCE seq_class_fornec MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_CLIENTES*/
CREATE TABLE CAD_CLIENTES(CODIGOCLIENTE BIGINT NOT NULL,NOMECLIENTE VARCHAR(150),PRIMARY KEY(CODIGOCLIENTE));
CREATE INDEX IDX_NOME_CLIENTE ON CAD_CLIENTES(NOMECLIENTE);
CREATE SEQUENCE seq_cad_clientes MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_PRODUTO*/
CREATE TABLE CAD_PRODUTO (CODIGOPRODUTO BIGINT NOT NULL,CODIGOPRODFORNECEDOR VARCHAR(255),CODIGO_BARRAS VARCHAR(255),DATACADASTRO TIMESTAMP,GRUPO BIGINT,NCM_SH BIGINT,MARCA VARCHAR(255),DESCRICAOPRODUTO VARCHAR(255),
    QUANTIDADE DECIMAL(12, 3),ESTOQUEMINIMO BIGINT,UNIDADE VARCHAR(3),VALORUNITPRODUTO DECIMAL(12, 3),VALORTABELAWEG DECIMAL(12, 3),FATORVALORVENDA BIGINT,
    IPI BIGINT,ICMS BIGINT,ATIVO BOOLEAN,USOOFICINA BOOLEAN,VERIFICAZERO BOOLEAN,LOCALIZACAO VARCHAR(255),PRIMARY KEY(CODIGOPRODUTO));
CREATE INDEX IDX_COD_PROD_FORNEC ON CAD_PRODUTO(CODIGOPRODFORNECEDOR);
CREATE INDEX IDX_DESC_PROD ON CAD_PRODUTO(DESCRICAOPRODUTO);
CREATE INDEX IDX_DT_CADASTRO ON CAD_PRODUTO(DATACADASTRO);
CREATE SEQUENCE seq_cod_prod_fornec MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_SERVICOS*/
CREATE TABLE CAD_SERVICOS(CODSERVICO BIGINT,DESCRICAOSERVICO VARCHAR(255),VALORVENDA DECIMAL(12,2),PRIMARY KEY(CODSERVICO));
CREATE INDEX IDX_DESCRICAO_SERV ON CAD_SERVICOS(DESCRICAOSERVICO);
CREATE SEQUENCE seq_servicos MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_SITUACAO*/
CREATE TABLE CAD_SITUACAO(CODIGOSITUACAO BIGINT,DESCRICAOSITUACAO VARCHAR(255),PRIMARY KEY(CODIGOSITUACAO));
CREATE INDEX IDX_DESCRICAO_SIT ON CAD_SITUACAO(DESCRICAOSITUACAO);
CREATE SEQUENCE seq_desc_sit MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*CAD_USUARIOS*/
CREATE TABLE CAD_USUARIOS(CODIGOUSER BIGINT,NOMEUSER VARCHAR(255),LOGIN VARCHAR(15),SENHA VARCHAR(8),GRUPO VARCHAR(255),PRIMARY KEY(CODIGOUSER));
CREATE INDEX IDX_NOMEUSER ON CAD_USUARIOS(NOMEUSER);
CREATE INDEX IDX_LOGIN ON CAD_USUARIOS(LOGIN);
CREATE INDEX IDX_NOMELOGIN ON CAD_USUARIOS(LOGIN, NOMEUSER);
CREATE SEQUENCE seq_cad_usuario MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DADOS_BOBINAGEM*/
CREATE TABLE DADOS_BOBINAGEM (
    ID BIGINT NOT NULL,OS VARCHAR(50),
    DATA_REALIZACAO TIMESTAMP, NOME_CLIENTE VARCHAR(255),PRAZO_FINALIZACAO TIMESTAMP,
    PRAZO_REBOBINAMENTO TIMESTAMP,PRAZO_MONTAGEM TIMESTAMP,
    PLACA VARCHAR(255),CATEGORIA VARCHAR(50),SERIE VARCHAR(255),MARCA VARCHAR(50),
    POTENCIA VARCHAR(255),MODELO VARCHAR(50),DATA_FABRICACAO TIMESTAMP,RPM VARCHAR(255),
    TENSAO VARCHAR(100),CORRENTE VARCHAR(255),ENROLAMENTO_FABRICA BOOLEAN,PATRIMONIO VARCHAR(255),
    FORMA_CONSTRUTIVA VARCHAR(255),CAIXA_LIGACAO VARCHAR(255),ACOPLAMENTO VARCHAR(255),
    CABOS VARCHAR(255),FECHAMENTO VARCHAR(255),COMPRIMENTO VARCHAR(255),DIAMETRO VARCHAR(255),
    RANHURAS VARCHAR(255),CAMADA VARCHAR(255),PASSO VARCHAR(255),ESPIRAS VARCHAR(255),
    FIO VARCHAR(255),SECCAO VARCHAR(50),PASSO_AUX VARCHAR(255),ESPIRAS_AUX VARCHAR(255),
    FIO_AUX VARCHAR(255),SECCAOAUX VARCHAR(50),PESO VARCHAR(255),LIGACAO VARCHAR(255),
    INFORCOES_ADICIONAIS LONG VARCHAR,CAUSA_QUEIMA VARCHAR(255),OBSERVACOES LONG VARCHAR,
    NOTA_FISCAL VARCHAR(255),NUMERO_FORMA VARCHAR(255),CALCO VARCHAR(255),ANEXOS BLOB,
    FECHADO BOOLEAN,VIBRACAO BOOLEAN,PALETE VARCHAR(10),PRIMARY KEY(ID));
CREATE INDEX IDX_PRAZOS ON DADOS_BOBINAGEM(PRAZOFINALIZACAO, PRAZOREBOBINAMENTO, PRAZOMONTAGEM);
CREATE SEQUENCE seq_dados_bobinagem MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DADOS_BOBINAGEM_ANEXOS*/
CREATE TABLE DADOS_BOBINAGEM_ANEXOS(
    ANEXO BIGINT NOT NULL,
    ID_DADOS_BOBINAGEM BIGINT NOT NULL,
    PATH_DOCUMENTO VARCHAR(255),
    PRIMARY KEY(ANEXO, ID_DADOS_BOBINAGEM)
);
/*DIM_EX_ANEL_FIXACAO*/
CREATE TABLE DIM_EX_ANEL_FIXACAO(
    CODCONTROLE BIGINT NOT NULL,CARCACA BIGINT,LINHA VARCHAR(255),POLOS INTEGER,
    WDIANT VARCHAR(15),W1DIANT VARCHAR(15),W2DIANT VARCHAR(15),W3DIANT VARCHAR(15),
    WTRAS VARCHAR(15),W1TRAS VARCHAR(15),W2TRAS VARCHAR(15),W3TRAS VARCHAR(15),
    COMPPASSCHAMAANELL VARCHAR(15),DIAMPASSCHAMAANELADIANT VARCHAR(15),
    DIAMPASSCHAMAANELATRAS VARCHAR(15),DIAMPASSCHAMAEIXOEDIANT VARCHAR(15),DIAMPASSCHAMAEIXOETRAS VARCHAR(15),
    FOLGAMAXIMADIANT VARCHAR(15),FOLGAMAXIMATRAS VARCHAR(15),PRIMARY KEY(CODCONTROLE));
CREATE INDEX IDX_ANF_CARCACA ON DIM_EX_ANEL_FIXACAO (CARCACA);
CREATE INDEX IDX_ANF_LINHA ON DIM_EX_ANEL_FIXACAO (LINHA);
CREATE INDEX IDX_ANF_CARC_LINHA ON DIM_EX_ANEL_FIXACAO (CARCACA, LINHA);
CREATE SEQUENCE dim_ex_anel_fix MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_CAIXA_LIGACAO*/
CREATE TABLE DIM_EX_CAIXA_LIGACAO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    W1 VARCHAR(255), --distância mínima entre furo e interior ou exterior do invólucro
    W2 VARCHAR(255), --idem W21 - L1 Comprimento Axial do Encaixe W22
    W3 VARCHAR(255), --idem
    LARGURAMINIMAJUNTAW1 VARCHAR(255), --Largura mínima da junta
    LARGURAMINIMAJUNTAW2 VARCHAR(255), --idem W21 - ØD1 Nominal W22
    FACETAMPAD1MINIMO VARCHAR(5), --ØD1 - W22
    FACETAMPAD1MAXIMO VARCHAR(5), --ØD1 - W22
    COMPRIMENTORADIALENCAIXE VARCHAR(5), --w1 - W22
    ENCAIXETAMPAMINIMO VARCHAR(10), --D3 - W22
    ENCAIXETAMPAMAXIMO VARCHAR(10), --D3 - W22
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_CXL_CARCACA ON DIM_EX_CAIXA_LIGACAO (CARCACA);
CREATE INDEX IDX_CXL_LINHA ON DIM_EX_CAIXA_LIGACAO (LINHA);
CREATE INDEX IDX_CXL_CARC_LINHA ON DIM_EX_CAIXA_LIGACAO (CARCACA, LINHA);
CREATE SEQUENCE dim_ex_caixa_ligacao MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_CARCACA*/
CREATE TABLE DIM_EX_CARCACA(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    CARCACAMINIMO VARCHAR(10),
    TAMPAMAXIMO VARCHAR(10),
    FOLGAMAXIMA VARCHAR(255),
    XMINIMO VARCHAR(10),
    YMINIMO VARCHAR(10),
    MINIMOCOMPPASSCHAMA VARCHAR(10),
    PRIMARY KEY(CODCONTROLE)
);
--COMMENT ON COLUMN DIM_EX_CARCACA.CARCACAMINIMO IS 'Ø minimo da carcaça';
--COMMENT ON COLUMN DIM_EX_CARCACA.TAMPAMAXIMO IS 'Ø maximo da tampa';
--COMMENT ON COLUMN DIM_EX_CARCACA.FOLGAMAXIMA IS 'ØTmax - ØCmin';
--COMMENT ON COLUMN DIM_EX_CARCACA.MINIMOCOMPPASSCHAMA IS 'y+x';
CREATE INDEX IDX_CRC_CARCACA ON DIM_EX_CARCACA (CARCACA);
CREATE INDEX IDX_CRC_LINHA ON DIM_EX_CARCACA (LINHA);
CREATE INDEX IDX_CRC_CARC_LINHA ON DIM_EX_CARCACA (CARCACA, LINHA);
CREATE SEQUENCE dim_ex_carcaca MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_EIXOS*/
CREATE TABLE DIM_EX_EIXOS(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    CDDIAMETRO VARCHAR(255),
    CDRD VARCHAR(255),
    CDMINIMO VARCHAR(255),
    CDMINIMO2 DECIMAL(12,3),
    CDMAXIMO VARCHAR(255),
    CDMAXIMO2 DECIMAL(12,3),
    CTDIAMETRO VARCHAR(255),
    CTRD VARCHAR(255),
    CTMINIMO VARCHAR(255),
    CTMINIMO2 VARCHAR(255),
    CTMAXIMO VARCHAR(255),
    CTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_EIXOS_CARCACA ON DIM_EX_EIXOS (CARCACA);
CREATE INDEX IDX_EIXOS_LINHA ON DIM_EX_EIXOS (LINHA);
CREATE INDEX IDX_EIXOS_POLOS ON DIM_EX_EIXOS (POLOS);
CREATE INDEX IDX_EIXOS_CARC_LINHA ON DIM_EX_EIXOS (CARCACA, LINHA);
CREATE INDEX IDX_EIXOS_CARC_PL_LINHA ON DIM_EX_EIXOS (CARCACA, POLOS, LINHA);
CREATE SEQUENCE dim_ex_eixos MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_PONTA_EIXO*/
CREATE TABLE DIM_EX_PONTA_EIXO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    MINIMO2 DECIMAL(12,3),
    MAXIMO2 DECIMAL(12,3),
    DIAMPONTAEIXO VARCHAR(10),
    RDEIXO VARCHAR(10),
    MINIMO VARCHAR(10),
    MAXIMO VARCHAR(10),
    BATIMENTO VARCHAR(10),
    DIAMCOLOVENTILADOR VARCHAR(10),
    RDCOLOVENTILADOR VARCHAR(10),
    COLOVENTMINIMO VARCHAR(10),
    COLOVENTMINIMO2 VARCHAR(255),
    COLOVENTMAXIMO VARCHAR(10),
    COLOVENTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_PTE_CARCACA ON DIM_EX_PONTA_EIXO (CARCACA);
CREATE INDEX IDX_PTE_POLOS ON DIM_EX_PONTA_EIXO (POLOS);
CREATE INDEX IDX_PTE_LINHA ON DIM_EX_PONTA_EIXO (LINHA);
CREATE INDEX IDX_PTE_CARC_LINHA ON DIM_EX_PONTA_EIXO (CARCACA, LINHA);
CREATE INDEX IDX_PTE_CARC_PL_LINHA ON DIM_EX_PONTA_EIXO (CARCACA, POLOS, LINHA);
CREATE SEQUENCE dim_ex_ponta_eixo MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_REF_ENCOSTO_ROLAMENTO*/
CREATE TABLE DIM_EX_REF_ENCOSTO_ROLAMENTO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    FURACAOPE VARCHAR(3),
    REFERENCIA VARCHAR(10),
    MINIMO VARCHAR(10),
    MAXIMO VARCHAR(10),
    MINIMO2 VARCHAR(10),
    MAXIMO2 VARCHAR(10),
    REFERENCIAENT VARCHAR(10),
    MINIMOENT VARCHAR(10),
    MAXIMOENT VARCHAR(10),
    MINIMO2ENT VARCHAR(10),
    MAXIMO2ENT VARCHAR(10),
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_RER_CARCACA ON DIM_EX_REF_ENCOSTO_ROLAMENTO (CARCACA);
CREATE INDEX IDX_RER_POLOS ON DIM_EX_REF_ENCOSTO_ROLAMENTO (POLOS);
CREATE INDEX IDX_RER_LINHA ON DIM_EX_REF_ENCOSTO_ROLAMENTO (LINHA);
CREATE INDEX IDX_RER_CARC_LINHA ON DIM_EX_REF_ENCOSTO_ROLAMENTO (CARCACA, LINHA);
CREATE INDEX IDX_RER_PL_CARC_LINHA ON DIM_EX_REF_ENCOSTO_ROLAMENTO (CARCACA, POLOS, LINHA);
CREATE SEQUENCE dim_ex_ref_encosto_rolamento MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_TAMPAS*/
CREATE TABLE DIM_EX_TAMPAS(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    TDDIAMETRO VARCHAR(255),
    TDRD VARCHAR(255),
    TDMINIMO VARCHAR(255),
    TDMINIMO2 VARCHAR(255),
    TDMAXIMO VARCHAR(255),
    TDMAXIMO2 VARCHAR(255),
    TTDIAMETRO VARCHAR(255),
    TTRD VARCHAR(255),
    TTMINIMO VARCHAR(255),
    TTMINIMO2 VARCHAR(255),
    TTMAXIMO VARCHAR(255),
    TTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_TMP_CARCACA ON DIM_EX_TAMPAS (CARCACA);
CREATE INDEX IDX_TMP_POLOS ON DIM_EX_TAMPAS (POLOS);
CREATE INDEX IDX_TMP_LINHA ON DIM_EX_TAMPAS (LINHA);
CREATE INDEX IDX_TMP_CARC_LINHA ON DIM_EX_TAMPAS (CARCACA, LINHA);
CREATE INDEX IDX_TMP_PL_CARC_LINHA ON DIM_EX_TAMPAS (CARCACA, POLOS, LINHA);
CREATE SEQUENCE dim_ex_tampas MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_TORQUE_PARAFUSOS*/
CREATE TABLE DIM_EX_TORQUE_PARAFUSOS(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    TAMPAS VARCHAR(10),
    TORQUETPMIN VARCHAR(10),
    TORQUETPMAX VARCHAR(10),
    ANEISFIX VARCHAR(10),
    TORQUEANEISMIN VARCHAR(10),
    TORQUEANEISMAX VARCHAR(10),
    BASECXLIG VARCHAR(10),
    TORQUEBASECXLIGMIN VARCHAR(10),
    TORQUEBASECXLIGMAX VARCHAR(10),
    CXLIGACAO VARCHAR(10),
    SAIDACABOS VARCHAR(10),
    TORQUECXLIGACAOMIN VARCHAR(10),
    TORQUECXLIGACAOMAX VARCHAR(10),
    PRIMARY KEY(CODCONTROLE)
);
CREATE INDEX IDX_TQP_CARCACA ON DIM_EX_TORQUE_PARAFUSOS (CARCACA);
CREATE INDEX IDX_TQP_LINHA ON DIM_EX_TORQUE_PARAFUSOS (LINHA);
CREATE INDEX IDX_TQP_CARC_LINHA ON DIM_EX_TORQUE_PARAFUSOS (CARCACA, LINHA);
CREATE SEQUENCE dim_ex_torque_parafusos MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*DIM_EX_VIBRACAO*/
CREATE TABLE DIM_EX_VIBRACAO(CODCONTROLE BIGINT NOT NULL,CARCACA BIGINT,LINHA VARCHAR(255),PADRAO VARCHAR(5),ESPECIAL VARCHAR(5),PRIMARY KEY(CODCONTROLE));
CREATE INDEX IDX_VBC_CARCACA ON DIM_EX_VIBRACAO (CARCACA);
CREATE INDEX IDX_VBC_LINHA ON DIM_EX_VIBRACAO (LINHA);
CREATE INDEX IDX_VBC_CARC_LINHA ON DIM_EX_VIBRACAO (CARCACA, LINHA);
CREATE SEQUENCE dim_ex_vibracao MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*MOV_AVALIACAO_FORNEC*/
CREATE TABLE MOV_AVALIACAO_FORNEC (
    CODAVALIACAO BIGINT NOT NULL,
    CODFORNEC BIGINT NOT NULL,
    DATAAVALIACAO VARCHAR(255),
    NOMEAVALIADOR VARCHAR(255),
    NEGOCIACAO BIGINT,
    SGQ BIGINT,
    SISTEMAGETAO BIGINT,
    VALIDADECERTIFICADO VARCHAR(255),
    NORMA VARCHAR(255),
    ESCOPO LONG VARCHAR,
    NAOCONFORMIDADE BIGINT,
    PERIODOINSPRECEBIMENTO1 TIMESTAMP,
    PERIODOINSPRECEBIMENTO2 TIMESTAMP,
    INSPRECEBIMENTO BIGINT,
    PONTOSOBTIDOS BIGINT,
    CLASSIFICACAO VARCHAR(255),
    PRIMARY KEY(CODAVALIACAO)
);
CREATE INDEX IDX_CODFORNEC ON MOV_AVALIACAO_FORNEC(CODFORNEC);
CREATE INDEX IDX_DATAAVALIACAO ON MOV_AVALIACAO_FORNEC(DATAAVALIACAO);
CREATE SEQUENCE seq_mov_aval_fornec MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*MOV_COTACOES*/
CREATE TABLE MOV_COTACOES(
    NUMEROREGISTROCOTACAO BIGINT,
    DATACOTACAO TIMESTAMP,
    CODCLIENTE BIGINT,
    NOMECONTATO VARCHAR(50),
    NOMEVENDEDOR VARCHAR(50),
    STATUS VARCHAR(255),
    CONDICAOPAGAMENTO VARCHAR(150),
    ENTREGA VARCHAR(150),
    ANOTACOESCOTACAO BLOB,
    PRIMARY KEY(NUMEROREGISTROCOTACAO)
);
CREATE SEQUENCE seq_mov_cotacoes MINVALUE 1 START WITH 1 INCREMENT BY 1;
/*MOV_DETALHES_RECEBIMENTO*/
CREATE TABLE MOV_DETALHES_RECEBIMENTO(
    RASTREABILIDADE BIGINT NOT NULL,
    CODIGOTESE BIGINT,
    LOTE VARCHAR(255),
    PROCESSO VARCHAR(255),
    RESPONSAVEL VARCHAR(255),
    INDICEAPROVACAO VARCHAR(10),
    INDICEPONTUALIDADE VARCHAR(10),
    RESPONSABELINSPECAO VARCHAR(255),
    APROVACAO BOOLEAN,
    PRIMARY KEY(RASTREABILIDADE)
);