CREATE TABLE DIM_EX_TAMPAS(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    TDDIAMETRO VARCHAR(255),
    TDRD VARCHAR(255),
    TDMINIMO VARCHAR(255),
    TDMINIMO2 VARCHAR(255),
    TDMAXIMO VARCHAR(255),
    TDMAXIMO2 VARCHAR(255),
    TTDIAMETRO VARCHAR(255),
    TTRD VARCHAR(255),
    TTMINIMO VARCHAR(255),
    TTMINIMO2 VARCHAR(255),
    TTMAXIMO VARCHAR(255),
    TTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);

CREATE INDEX IDX_TMP_CARCACA ON DIM_EX_TAMPAS (CARCACA);
CREATE INDEX IDX_TMP_POLOS ON DIM_EX_TAMPAS (POLOS);
CREATE INDEX IDX_TMP_LINHA ON DIM_EX_TAMPAS (LINHA);
CREATE INDEX IDX_TMP_CARC_LINHA ON DIM_EX_TAMPAS (CARCACA, LINHA);
CREATE INDEX IDX_TMP_PL_CARC_LINHA ON DIM_EX_TAMPAS (CARCACA, POLOS, LINHA);

CREATE SEQUENCE dim_ex_tampas
MINVALUE 1
START WITH 1
INCREMENT BY 1;