CREATE TABLE MOV_AVALIACAO_FORNEC (
    CODAVALIACAO BIGINT NOT NULL,
    CODFORNEC BIGINT NOT NULL,
    DATAAVALIACAO VARCHAR(255),
    NOMEAVALIADOR VARCHAR(255),
    NEGOCIACAO BIGINT,
    SGQ BIGINT,
    SISTEMAGETAO BIGINT,
    VALIDADECERTIFICADO VARCHAR(255),
    NORMA VARCHAR(255),
    ESCOPO LONG VARCHAR,
    NAOCONFORMIDADE BIGINT,
    PERIODOINSPRECEBIMENTO1 TIMESTAMP,
    PERIODOINSPRECEBIMENTO2 TIMESTAMP,
    INSPRECEBIMENTO BIGINT,
    PONTOSOBTIDOS BIGINT,
    CLASSIFICACAO VARCHAR(255),
    PRIMARY KEY(CODAVALIACAO)
);

CREATE INDEX IDX_CODFORNEC ON MOV_AVALIACAO_FORNEC(CODFORNEC);
CREATE INDEX IDX_DATAAVALIACAO ON MOV_AVALIACAO_FORNEC(DATAAVALIACAO);

CREATE SEQUENCE seq_mov_aval_fornec
MINVALUE 1
START WITH 1
INCREMENT BY 1;