CREATE TABLE CAD_CLIENTES(
    CODIGOCLIENTE BIGINT NOT NULL,
    NOMECLIENTE VARCHAR(150),
    PRIMARY KEY(CODIGOCLIENTE),
);

CREATE INDEX IDX_NOME_CLIENTE ON CAD_CLIENTES(NOMECLIENTE);

CREATE SEQUENCE seq_cad_clientes
MINVALUE 1
START WITH 1
INCREMENT BY 1;