CREATE TABLE DIM_EX_VIBRACAO(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    LINHA VARCHAR(255),
    PADRAO VARCHAR(5),
    ESPECIAL VARCHAR(5),
    PRIMARY KEY(CODCONTROLE)
);

CREATE INDEX IDX_VBC_CARCACA ON DIM_EX_VIBRACAO (CARCACA);
CREATE INDEX IDX_VBC_LINHA ON DIM_EX_VIBRACAO (LINHA);
CREATE INDEX IDX_VBC_CARC_LINHA ON DIM_EX_VIBRACAO (CARCACA, LINHA);

CREATE SEQUENCE dim_ex_vibracao
MINVALUE 1
START WITH 1
INCREMENT BY 1;