CREATE TABLE CAD_SITUACAO(
    CODIGOSITUACAO BIGINT,
    DESCRICAOSITUACAO VARCHAR(255),
    PRIMARY KEY(CODIGOSITUACAO)
);

CREATE INDEX IDX_DESCRICAO_SIT ON CAD_SITUACAO(DESCRICAOSITUACAO);

CREATE SEQUENCE seq_desc_sit
MINVALUE 1
START WITH 1
INCREMENT BY 1;