CREATE TABLE CAD_CLASSIFICACAO_FORNEC(
    CODCLASSIFICACAO BIGINT,
    DESCRICAOCLASSIFICAO VARCHAR(255),
    PRIMARY KEY(CODCLASSIFICACAO)
);

CREATE SEQUENCE seq_class_fornec
MINVALUE 1
START WITH 1
INCREMENT BY 1;