CREATE TABLE MOV_DETALHES_RECEBIMENTO(
    RASTREABILIDADE BIGINT NOT NULL,
    CODIGOTESE BIGINT,
    LOTE VARCHAR(255),
    PROCESSO VARCHAR(255),
    RESPONSAVEL VARCHAR(255),
    INDICEAPROVACAO VARCHAR(10),
    INDICEPONTUALIDADE VARCHAR(10),
    RESPONSABELINSPECAO VARCHAR(255),
    APROVACAO BOOLEAN,
    PRIMARY KEY(RASTREABILIDADE)
);