CREATE TABLE CAD_ASSINATURAS (
    CODIGO BIGINT NOT NULL,
    NOME VARCHAR(30),
    SENHA VARCHAR(8),
    ASSELETRONICA BLOB,
    PRIMARY KEY(CODIGO)
);

CREATE INDEX IDX_NOME ON CAD_ASSINATURAS(NOME);

CREATE SEQUENCE seq_assinaturas
MINVALUE 1
START WITH 1
INCREMENT BY 1;