CREATE TABLE MOV_COTACOES(
    NUMEROREGISTROCOTACAO BIGINT,
    DATACOTACAO TIMESTAMP,
    CODCLIENTE BIGINT,
    NOMECONTATO VARCHAR(50),
    NOMEVENDEDOR VARCHAR(50),
    STATUS VARCHAR(255),
    CONDICAOPAGAMENTO VARCHAR(150),
    ENTREGA VARCHAR(150),
    ANOTACOESCOTACAO BLOB,
    PRIMARY KEY(NUMEROREGISTROCOTACAO)
);

CREATE SEQUENCE seq_mov_cotacoes
MINVALUE 1
START WITH 1
INCREMENT BY 1;