CREATE TABLE CAD_MARCAS(
    CODIGO BIGINT NOT NULL,
    MARCA VARCHAR(255) NOT NULL,
    PRIMARY KEY(CODIGO)
);

CREATE INDEX IDX_MARCA ON CAD_MARCAS(MARCA);

CREATE SEQUENCE seq_cad_marcas 
MINVALUE 1 
START WITH 1 
INCREMENT BY 1;