CREATE TABLE CAD_USUARIOS(
    CODIGOUSER BIGINT,
    NOMEUSER VARCHAR(255),
    LOGIN VARCHAR(15),
    SENHA VARCHAR(8),
    GRUPO VARCHAR(255),
    PRIMARY KEY(CODIGOUSER)
);

CREATE INDEX IDX_NOMEUSER ON CAD_USUARIOS(NOMEUSER);
CREATE INDEX IDX_LOGIN ON CAD_USUARIOS(LOGIN);
CREATE INDEX IDX_NOMELOGIN ON CAD_USUARIOS(LOGIN, NOMEUSER);

CREATE SEQUENCE seq_cad_usuario
MINVALUE 1
START WITH 1
INCREMENT BY 1;