CREATE TABLE DIM_EX_EIXOS(
    CODCONTROLE BIGINT NOT NULL,
    CARCACA BIGINT,
    POLOS INTEGER,
    LINHA VARCHAR(255),
    CDDIAMETRO VARCHAR(255),
    CDRD VARCHAR(255),
    CDMINIMO VARCHAR(255),
    CDMINIMO2 DECIMAL(12,3),
    CDMAXIMO VARCHAR(255),
    CDMAXIMO2 DECIMAL(12,3),
    CTDIAMETRO VARCHAR(255),
    CTRD VARCHAR(255),
    CTMINIMO VARCHAR(255),
    CTMINIMO2 VARCHAR(255),
    CTMAXIMO VARCHAR(255),
    CTMAXIMO2 VARCHAR(255),
    PRIMARY KEY(CODCONTROLE)
);

CREATE INDEX IDX_EIXOS_CARCACA ON DIM_EX_EIXOS (CARCACA);
CREATE INDEX IDX_EIXOS_LINHA ON DIM_EX_EIXOS (LINHA);
CREATE INDEX IDX_EIXOS_POLOS ON DIM_EX_EIXOS (POLOS);
CREATE INDEX IDX_EIXOS_CARC_LINHA ON DIM_EX_EIXOS (CARCACA, LINHA);
CREATE INDEX IDX_EIXOS_CARC_PL_LINHA ON DIM_EX_EIXOS (CARCACA, POLOS, LINHA);

CREATE SEQUENCE dim_ex_eixos
MINVALUE 1
START WITH 1
INCREMENT BY 1;